# Set up notification options
notifications: 
  email:
    recipients:
      - amanprtpsingh@gmail.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

# specify language
language: python

sudo: enabled

# specify language options
python:
  - '2.7'

# configure which branches to run
branches:
  # whitelist
  only:
    - master

## begin build steps
####################

before_install:
  - sudo apt-get update -qq
  - python -m pip install jupyter
  - python -m pip install ganga
  - python -m pip install ipython --upgrade
  - ipython profile create
  - cp -r test/ $(ipython locate)/extensions/
  - mv $(ipython locate)/extensions/test $(ipython locate)/extensions/extension
  - echo "c.InteractiveShellApp.extensions.append('extension')" >> $(ipython profile locate default)/ipython_kernel_config.py

install:
  - cd $TRAVIS_BUILD_DIR/extension/
  - python -m pip install .
  - jupyter nbextension install --py gangaextension --sys-prefix
  - jupyter nbextension enable --py gangaextension --sys-prefix
  - jupyter serverextension enable --py gangaextension --sys-prefix

script:
  - cd $TRAVIS_BUILD_DIR/
  - jupyter-nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1000 notebooks/help_robinson.ipynb